"use strict";
exports.__esModule = true;
var dia9ClaseBooks_1 = require("./dia9ClaseBooks");
var dia9ClaseLibrery_1 = require("./dia9ClaseLibrery");
var libro1 = new dia9ClaseBooks_1.Book("100 años de soledad", 158, "Gabriel", "Gabriel Marquez", "Porrua");
//console.log (libro1); 
var libro2 = new dia9ClaseBooks_1.Book("La estrella de Lisa", 58, "Gabrielita", "TANIA MORALES", "Editores");
//console.log (libro2); 
var libro3 = new dia9ClaseBooks_1.Book("La miseria del torpe", 0.01, "Charlito", "Soto Godinez", "Delfines");
//console.log (libro3); 
var libreria1 = new dia9ClaseLibrery_1.Library([libro1, libro2, libro3], "calle Paltatitla", "taniaMorales"); //clase al ultimo de agrgan estos datos ;
// console.log(libreria1);
var comprobacionMetodo = libreria1.todosLibros();
// console.log(comprobacionMetodo);
var cuantosLibros = libreria1.getNumberOfBooks();
//console.log(cuantosLibros);
var esAutorIgual = libreria1.findByAutor("TANIA MORALES");
console.log("es el autor**********************");
console.log(esAutorIgual);
